title: Sumiya Fatema
logo: <img src="https://github.com/user-attachments/assets/6c19fa48-2b4d-453d-8a52-6d3f5a259794" alt="Headshot" width="250">
description: >
  ğŸ‘©â€ğŸ’» Cloud Computing | AWS Projects | Data Engineering  
  Welcome to my GitHub Portfolio! Explore my work in data ingestion, security, analytics, and AWS services.

  <br><br>
  <img src="https://github.com/user-attachments/assets/b81a9259-eba8-41c5-95fb-3201544a94e5" alt="AWS Academy Graduate - Cloud Foundations Badge" width="250">
  <br>
  <a href="https://www.credly.com/badges/35b14497-b739-49f3-a751-4d3cf7646dde/public_url" target="_blank">View my AWS Academy Cloud Foundations Credential</a>
theme: jekyll-theme-minimal
show_downloads: false
google_analytics:
